if(cpr_FOUND)
  message(STATUS "CPR Library found")
  add_library(RoPP::cpr UNKNOWN IMPORTED)
  set_target_properties(RoPP::cpr PROPERTIES IMPORTED_LOCATION "${cpr_LIBRARIES}")
  set_target_properties(RoPP::cpr PROPERTIES INTERFACE_INCLUDE_DIRECTORIES "${cpr_INCLUDE_DIRS}")
else()
  message(STATUS "CPR Library not found, using cpr target directly")
  add_library(RoPP::cpr ALIAS cpr)
endif()